# Generated by Django 5.2 on 2025-04-27 15:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='lesson',
            name='access_level',
            field=models.CharField(choices=[('basic', 'Basic - Unregistered Users'), ('intermediate', 'Intermediate - Registered Users'), ('advanced', 'Advanced - Paid Users')], default='intermediate', help_text='Minimum access level required to view this lesson', max_length=20),
        ),
        migrations.AddField(
            model_name='lesson',
            name='basic_content',
            field=models.TextField(blank=True, help_text='Preview content for unregistered users', null=True),
        ),
        migrations.AddField(
            model_name='lesson',
            name='intermediate_content',
            field=models.TextField(blank=True, help_text='Limited content for registered users', null=True),
        ),
        migrations.AddField(
            model_name='resource',
            name='premium',
            field=models.BooleanField(default=False, help_text='Whether this resource requires a premium subscription'),
        ),
        migrations.AlterField(
            model_name='lesson',
            name='content',
            field=models.TextField(help_text='Full content visible to all users (or premium content if access_level is set)'),
        ),
    ]
